"""Growth brief content for Priority 2–4 outreach targets."""

BRIEFS_P2_P4: list[dict] = [
    {
        "slug": "everplans",
        "name": "Everplans",
        "logo_ext": "svg",
        "about": "Digital vault and life-planning platform for financial advisors inside Precoa.",
        "headline": "We believe we can help Everplans lift advisor-led vault activation to 50% of invited clients.",
        "insight": "You are extending advisor distribution for enterprise vaults and life-planning workflows. Families still stall when the first upload feels abstract before they see what advisors actually organize for them.",
        "opps": [
            ("01", "Show a sample vault outcome before advisor handoff", "Families need to see organized documents, not empty folders. We'd start by previewing a realistic vault, then invite their first upload.", "journey", [("Advisor invite", False), ("Vault preview", True), ("First doc added", False)]),
            ("02", "Map advisor invite through first family milestone", "Advisor-led growth lives in completion, not opens. We'd start by instrumenting invite through first shared plan.", "funnel", [("Invite sent", 100, False), ("Account created", 62, False), ("Plan started", 41, True)]),
            ("03", "Align advisor and family views on the same timeline", "Split experiences confuse both sides. We'd start by using one milestone language in-app and in advisor tools.", None, None),
        ],
        "measures": [
            "Invited families creating accounts within seven days.",
            "First document uploaded within 48 hours of signup.",
            "Advisor cohorts beating prior activation by launch month.",
        ],
    },
    {
        "slug": "faireez",
        "name": "Faireez",
        "logo_ext": "svg",
        "about": "Hotel-style in-building housekeeping sold as a landlord amenity in major U.S. cities.",
        "headline": "We believe we can help Faireez lift resident booking conversion to 35% of building invites.",
        "insight": "You are scaling building-amenity housekeeping where residents choose slots and trust before they grant access. The public booking flow is where that commitment is won or lost.",
        "opps": [
            ("01", "Preview a typical clean before residents pick a slot", "Residents wonder what they are buying. We'd start by showing scope, timing, and price for a standard visit, then open scheduling.", "journey", [("Building invite", False), ("Visit preview", True), ("Slot booked", False)]),
            ("02", "Map invite through first completed service", "Landlord deals fail when residents never book. We'd start by tracking invite through first completed clean.", "funnel", [("Invite opened", 100, False), ("Slot selected", 58, False), ("Service complete", 36, True)]),
            ("03", "Give property managers a building-level activation view", "PMs sell amenities with proof. We'd start by packaging activation per property for their renewals.", None, None),
        ],
        "measures": [
            "Residents booking within 14 days of building invite.",
            "First service completed within seven days of booking.",
            "Repeat bookings within 30 days of the first visit.",
        ],
    },
    {
        "slug": "foodini",
        "name": "Foodini",
        "logo_ext": "svg",
        "about": "Restaurant platform for personalized menus and dietary compliance, including SB 68 tools.",
        "headline": "We believe we can help Foodini lift diner engagement on partner menus by 30%.",
        "insight": "You are rolling Personalized Menu features and compliance tooling into partner restaurants. Diners still need to feel dietary intelligence working before they change how they order.",
        "opps": [
            ("01", "Show personalized filters working on a real menu", "Diners skim past claims. We'd start by demonstrating filters on a live menu item, then ask for profile save.", "journey", [("Menu scan", False), ("Filter demo", True), ("Profile saved", False)]),
            ("02", "Map scan-to-order on partner locations", "Partner value shows up in orders, not installs. We'd start by instrumenting scan through completed order.", "funnel", [("QR opened", 100, False), ("Items filtered", 64, False), ("Order placed", 39, True)]),
            ("03", "Package compliance wins for operator sales", "Operators buy proof. We'd start by surfacing SB 68 readiness per venue in partner dashboards.", None, None),
        ],
        "measures": [
            "Scans resulting in a saved dietary profile.",
            "Orders using personalized recommendations per location.",
            "Partner locations active weekly after onboarding.",
        ],
    },
    {
        "slug": "home-alliance",
        "name": "Home Alliance",
        "logo_ext": "svg",
        "about": "Consumer marketplace for booking vetted in-home services.",
        "headline": "We believe we can help Home Alliance lift booking completion to 55% of started requests.",
        "insight": "You promise fast, reliable in-home service booking. Consumers still abandon when pricing, arrival windows, and pro credentials are unclear before they confirm.",
        "opps": [
            ("01", "Surface pro credentials and price before confirm", "Home services spike anxiety. We'd start by showing who is coming and the all-in price, then ask for payment.", "journey", [("Service selected", False), ("Pro + price shown", True), ("Booked", False)]),
            ("02", "Map request start through appointment confirmed", "Every extra step costs conversion on mobile. We'd start by mapping drop-off across the public booking path.", "funnel", [("Request started", 100, False), ("Details entered", 68, False), ("Appointment confirmed", 44, True)]),
            ("03", "Align SMS and web status on one timeline", "Split updates drive support calls. We'd start by mirroring the same milestones in both channels.", None, None),
        ],
        "measures": [
            "Started requests reaching confirmed appointment.",
            "Median time from start to confirm under 10 minutes.",
            "First-service completion rate within 48 hours of booking.",
        ],
    },
    {
        "slug": "ivideon",
        "name": "Ivideon",
        "logo_ext": "svg",
        "about": "Cloud video surveillance with analytics for SMB, enterprise, and home users.",
        "headline": "We believe we can help Ivideon lift trial-to-paid conversion on advanced analytics to 40%.",
        "insight": "You are pushing sophisticated camera analytics across verticals. Buyers still need to see detections working on their scene before they upgrade plans or add cameras.",
        "opps": [
            ("01", "Offer a live analytics preview on sample footage", "Feature lists do not sell vision. We'd start by showing detections on their use case clip, then ask for camera connect.", "journey", [("Trial start", False), ("Analytics preview", True), ("Camera online", False)]),
            ("02", "Map camera online through first alert delivered", "Revenue follows proof of monitoring. We'd start by tracking pairing through first meaningful notification.", "funnel", [("Account created", 100, False), ("First stream live", 61, False), ("Paid tier active", 38, True)]),
            ("03", "Reuse the same trust pattern for home and business tiers", "Two audiences, one brand. We'd start by aligning upgrade moments across both paths.", None, None),
        ],
        "measures": [
            "Trials connecting a camera within 24 hours.",
            "First analytics alert within 72 hours of go-live.",
            "Upgrade rate among accounts with sustained alerts.",
        ],
    },
    {
        "slug": "mealpal",
        "name": "MealPal",
        "logo_ext": "svg",
        "about": "Lunch subscription marketplace for affordable pickup near work.",
        "headline": "We believe we can help MealPal lift new member first pickup to 60% within seven days.",
        "insight": "You are growing restaurant partners while keeping pickup dead simple for hybrid workers. Members still churn when the first lunch feels uncertain before they leave the desk.",
        "opps": [
            ("01", "Preview tomorrow's pickup before membership commit", "Busy workers need certainty. We'd start by showing real meals near them tomorrow, then ask for plan start.", "journey", [("Zip entered", False), ("Meal preview", True), ("Plan started", False)]),
            ("02", "Map signup through first redeemed meal", "First pickup is the habit moment. We'd start by instrumenting signup through scan at restaurant.", "funnel", [("Signup", 100, False), ("Plan active", 72, False), ("First pickup", 48, True)]),
            ("03", "Localize onboarding per office cluster", "Density varies by city block. We'd start by tuning copy and restaurant sets per launch market.", None, None),
        ],
        "measures": [
            "New members redeeming within seven days of signup.",
            "Second pickup within 14 days of the first.",
            "Partner restaurant utilization per lunch window.",
        ],
    },
    {
        "slug": "medbill-ai",
        "name": "Granted Health",
        "logo_ext": "svg",
        "about": "Consumer health finance product (formerly Medbill AI) preparing for public launch.",
        "headline": "We believe we can help Granted Health lift bill-upload completion to 65% of signups.",
        "insight": "You are moving from stealth toward launch with a founding growth hire. Users still hesitate when uploading medical bills before they know what advocacy or savings look like.",
        "opps": [
            ("01", "Show a sample savings outcome before bill upload", "Bills feel sensitive. We'd start by previewing a resolved claim story, then request the first document.", "journey", [("Landing", False), ("Outcome preview", True), ("Bill uploaded", False)]),
            ("02", "Map signup through first actionable insight", "PLG needs a fast win. We'd start by tracking signup through first personalized recommendation.", "funnel", [("Signup", 100, False), ("Bill parsed", 58, False), ("Insight delivered", 42, True)]),
            ("03", "Design launch cohorts separately from waitlist", "Blended metrics will lie. We'd start by tagging users by acquisition source from day one.", None, None),
        ],
        "measures": [
            "Signups uploading a bill within 48 hours.",
            "First insight delivered within 24 hours of upload.",
            "Return visits within seven days of first insight.",
        ],
    },
    {
        "slug": "mobokey",
        "name": "MoboKey",
        "logo_ext": "svg",
        "about": "Contactless car access hardware for rentals, fleets, and Turo hosts.",
        "headline": "We believe we can help MoboKey lift partner fleet activation to 70% of shipped devices.",
        "insight": "You are pushing into car-rental and fleet partners with contactless access hardware. Operators still stall when install steps and renter handoff are unclear before the first live rental.",
        "opps": [
            ("01", "Walk operators through a live unlock demo before install", "Hardware needs proof. We'd start by showing a successful phone unlock on demo kit, then open install checklist.", "journey", [("Partner signup", False), ("Live unlock demo", True), ("Device installed", False)]),
            ("02", "Map ship-to-first rental across partner cohorts", "Devices without rentals do not renew. We'd start by tracking shipment through first renter unlock.", "funnel", [("Device shipped", 100, False), ("Installed", 66, False), ("First rental unlock", 45, True)]),
            ("03", "Package Turo host onboarding separately from fleet", "Segments behave differently. We'd start by templating paths per partner type.", None, None),
        ],
        "measures": [
            "Shipped devices reporting installs within 14 days.",
            "First renter unlock within seven days of install.",
            "Partner cohorts beating prior activation baseline.",
        ],
    },
    {
        "slug": "ourfamilywizard",
        "name": "OurFamilyWizard",
        "logo_ext": "svg",
        "about": "Co-parenting communication app adopted through family law professionals.",
        "headline": "We believe we can help OurFamilyWizard lift professional-referred family activation to 55%.",
        "insight": "You are hiring liaisons to champion the platform to legal professionals. Families introduced through attorneys still need clarity before they message or share calendars.",
        "opps": [
            ("01", "Preview the co-parent timeline before account setup", "High-conflict moments need reassurance. We'd start by showing how messaging and calendars work, then invite signup.", "journey", [("Attorney referral", False), ("Product preview", True), ("Account live", False)]),
            ("02", "Map referral through first shared calendar event", "Activation is shared usage. We'd start by instrumenting referral through first coordinated entry.", "funnel", [("Invite sent", 100, False), ("Both parents active", 54, False), ("First shared event", 37, True)]),
            ("03", "Give liaisons a cohort view they can present", "Professionals need outcomes. We'd start by packaging activation per firm for liaison follow-up.", None, None),
        ],
        "measures": [
            "Referred families with both parents active within 14 days.",
            "First message or calendar share within seven days of activation.",
            "Professional cohorts beating prior referral conversion.",
        ],
    },
    {
        "slug": "push-health",
        "name": "Push Health",
        "logo_ext": "svg",
        "about": "Telehealth platform for independent clinicians and transparent prescriptions.",
        "headline": "We believe we can help Push Health lift patient visit completion to 75% of started intakes.",
        "insight": "You connect patients with independent clinicians for virtual care and prescriptions. Patients still drop when pricing, clinician choice, and next steps are opaque before they pay.",
        "opps": [
            ("01", "Show clinician credentials and visit price upfront", "Telehealth competes on trust. We'd start by surfacing who they will see and the all-in cost, then start intake.", "journey", [("Condition selected", False), ("Clinician + price", True), ("Visit paid", False)]),
            ("02", "Map intake start through prescription or care plan", "Revenue follows completed visits. We'd start by mapping abandonment across intake and payment.", "funnel", [("Intake started", 100, False), ("Payment complete", 69, False), ("Visit complete", 52, True)]),
            ("03", "Align clinician and patient status language", "Two-sided confusion drives support. We'd start by mirroring milestones on both dashboards.", None, None),
        ],
        "measures": [
            "Started intakes reaching paid visit.",
            "Median time from start to visit complete under 48 hours.",
            "Repeat visits within 60 days for chronic cohorts.",
        ],
    },
    {
        "slug": "tandym",
        "name": "Tandym",
        "logo_ext": "svg",
        "about": "Branded-card payments network integrated into PublicSquare's merchant fintech stack.",
        "headline": "We believe we can help Tandym lift merchant go-live to first card swipe to 50%.",
        "insight": "You are rolling branded-card capability across a larger merchant network after the PublicSquare integration. Merchants still hesitate when developer setup and customer value are unclear before launch.",
        "opps": [
            ("01", "Preview card rewards on a sample checkout before dev work", "Merchants buy outcomes. We'd start by showing shopper-facing rewards on a demo store, then open integration steps.", "journey", [("Merchant interest", False), ("Checkout demo", True), ("Integration started", False)]),
            ("02", "Map integration through first live transaction", "Go-live without volume does not stick. We'd start by tracking technical setup through first swipe.", "funnel", [("Signup", 100, False), ("Integration live", 57, False), ("First transaction", 39, True)]),
            ("03", "Segment PublicSquare merchants from net-new cohorts", "Channels will diverge. We'd start by tagging merchants by acquisition source at onboarding.", None, None),
        ],
        "measures": [
            "Integrations reaching first transaction within 30 days.",
            "Repeat transaction weeks among live merchants.",
            "Developer time-to-go-live versus prior baseline.",
        ],
    },
    {
        "slug": "tlon",
        "name": "Tlon",
        "logo_ext": "svg",
        "about": "Privacy-forward messenger evolving into a social OS with built-in AI agents.",
        "headline": "We believe we can help Tlon lift new-account week-one retention to 35%.",
        "insight": "You are shipping a cryptographic AI agent into every new Messenger account. Users still need to feel the agent and identity story click in the first session before they explore deeper social features.",
        "opps": [
            ("01", "Make the first agent interaction feel complete before invites", "Novelty fades fast. We'd start by delivering a satisfying agent exchange, then invite contacts or groups.", "journey", [("Account created", False), ("Agent moment", True), ("First invite", False)]),
            ("02", "Map signup through day-seven return", "Social OS growth is habit. We'd start by mapping where first-week users stall after onboarding.", "funnel", [("Signup", 100, False), ("Day 2 return", 46, False), ("Day 7 active", 28, True)]),
            ("03", "Keep agent, chat, and identity visuals consistent", "Fragmented UI reads experimental. We'd start by reusing trust components across surfaces.", None, None),
        ],
        "measures": [
            "New accounts finishing the first agent session.",
            "Day-three return among users who complete session one.",
            "Invites sent within seven days of signup.",
        ],
    },
    {
        "slug": "upwards",
        "name": "Upwards",
        "logo_ext": "svg",
        "about": "Care-as-a-service platform for employers and governments connecting families and providers.",
        "headline": "We believe we can help Upwards lift family-to-provider match completion to 60%.",
        "insight": "You are scaling across employers and local governments where families and providers commit in public-facing flows. Those first booking and verification moments need to feel guided, not bureaucratic.",
        "opps": [
            ("01", "Show provider credentials before family commits to match", "Childcare decisions are high stakes. We'd start by surfacing provider proof and visit structure, then open scheduling.", "journey", [("Family enrolled", False), ("Provider preview", True), ("Match confirmed", False)]),
            ("02", "Map enrollment through first completed care session", "Funding follows utilization. We'd start by instrumenting enrollment through first session logged.", "funnel", [("Enrolled", 100, False), ("Provider matched", 63, False), ("First session", 41, True)]),
            ("03", "Localize flows per employer and municipality", "Programs differ by sponsor. We'd start by templating copy and steps per cohort without cloning blindly.", None, None),
        ],
        "measures": [
            "Enrolled families matched within 14 days.",
            "First care session within 21 days of match.",
            "Provider utilization per employer cohort.",
        ],
    },
    {
        "slug": "autostoday",
        "name": "AutosToday",
        "logo_ext": "svg",
        "about": "Consumer car marketplace and app connecting buyers, sellers, and dealerships.",
        "headline": "We believe we can help AutosToday lift buyer lead-to-test-drive booking to 40%.",
        "insight": "You are scaling a marketplace where high-friction steps like financing previews and seller contact scare mobile buyers. The path from listing view to scheduled test drive is where trust compounds.",
        "opps": [
            ("01", "Surface all-in price and seller proof on the listing", "Auto shoppers compare instantly. We'd start by showing fees and seller history on the listing, then open contact.", "journey", [("Listing view", False), ("Price + seller proof", True), ("Contact sent", False)]),
            ("02", "Map browse through test-drive scheduled", "Dealer ROI is appointments. We'd start by tracking listing click through confirmed visit.", "funnel", [("Listing click", 100, False), ("Lead form", 58, False), ("Test drive booked", 35, True)]),
            ("03", "Separate dealer inventory from private-party paths", "Two supply types, two anxieties. We'd start by tailoring proof moments per listing type.", None, None),
        ],
        "measures": [
            "Listing views producing a qualified lead.",
            "Test drives booked within seven days of lead.",
            "Dealer response time to first contact.",
        ],
    },
    {
        "slug": "bambino-sitters",
        "name": "Bambino Sitters",
        "logo_ext": "svg",
        "about": "Neighborhood babysitting marketplace with parent and sitter referrals.",
        "headline": "We believe we can help Bambino lift parent first booking to 45% of signups.",
        "insight": "You are evolving referral mechanics while scaling dependable sitters and on-the-spot bookings. Parents still need neighbor-trust signals before they book someone new for their kids.",
        "opps": [
            ("01", "Lead with sitter social proof before payment", "Child safety is non-negotiable. We'd start by showing mutual connections and sitter history, then confirm booking.", "journey", [("Parent signup", False), ("Sitter proof", True), ("Booking paid", False)]),
            ("02", "Map signup through first completed sit", "Habit starts with one good night out. We'd start by instrumenting signup through completed session.", "funnel", [("Signup", 100, False), ("Sitter contacted", 64, False), ("Sit complete", 40, True)]),
            ("03", "Tune referral rewards without confusing sitter vs parent", "Policy changes affect growth. We'd start by clarifying eligibility in-product before checkout.", None, None),
        ],
        "measures": [
            "Signups completing a first booking within 14 days.",
            "Second booking within 45 days of the first.",
            "Sitter acceptance rate on first requests.",
        ],
    },
    {
        "slug": "careclinic",
        "name": "CareClinic",
        "logo_ext": "svg",
        "about": "Patient-facing remote monitoring and personal health tracking for clinics and pharmacies.",
        "headline": "We believe we can help CareClinic lift patient program enrollment completion to 55%.",
        "insight": "You support clinics and pharmacies keeping patients engaged between visits. Patients still abandon when program value and data use are unclear before they connect devices or logs.",
        "opps": [
            ("01", "Preview care plan benefits before device or log setup", "Patients fear busywork. We'd start by showing what their clinician will see, then request first data.", "journey", [("Invite opened", False), ("Plan preview", True), ("First log", False)]),
            ("02", "Map invite through seven-day adherence", "RPM contracts need usage. We'd start by tracking invite through week-one adherence.", "funnel", [("Invite sent", 100, False), ("Account created", 60, False), ("Week-one adherent", 38, True)]),
            ("03", "Align clinic, pharmacy, and patient milestone language", "Three audiences, one program. We'd start by using the same status names everywhere.", None, None),
        ],
        "measures": [
            "Invited patients enrolling within 72 hours.",
            "Week-one adherence among enrollees.",
            "Clinic cohorts beating prior enrollment baselines.",
        ],
    },
    {
        "slug": "carpooll",
        "name": "Carpooll",
        "logo_ext": "svg",
        "about": "Canadian long-distance rideshare app scaling toward 15,000+ members.",
        "headline": "We believe we can help Carpooll lift first trip booked to 38% of new members.",
        "insight": "You have momentum in the Canadian market with growing App Store rank. New members still need trust in drivers and trip clarity before they message or book a seat.",
        "opps": [
            ("01", "Show trip and driver proof before first message", "Rideshare trust is personal. We'd start by surfacing verification and trip history, then open chat.", "journey", [("Profile created", False), ("Driver proof", True), ("First message", False)]),
            ("02", "Map signup through confirmed seat", "Browse without booking does not scale. We'd start by mapping signup through booked trip.", "funnel", [("Signup", 100, False), ("Search to contact", 59, False), ("Trip booked", 36, True)]),
            ("03", "Localize onboarding for each corridor launch", "Corridors differ. We'd start by tuning copy and verification steps per route.", None, None),
        ],
        "measures": [
            "New members verifying within 48 hours.",
            "First trip booked within 21 days of signup.",
            "Second trip within 60 days of the first ride.",
        ],
    },
    {
        "slug": "cirtru",
        "name": "Cirtru",
        "logo_ext": "svg",
        "about": "Neighborhood and rental community platform scaling organic discovery.",
        "headline": "We believe we can help Cirtru lift visitor-to-signup conversion to 12% on neighborhood pages.",
        "insight": "You are pushing aggressive top-of-funnel growth with neighborhood content. Visitors still bounce when local value is abstract before they see real posts or listings near them.",
        "opps": [
            ("01", "Lead with hyperlocal content before account ask", "SEO traffic needs instant relevance. We'd start by showing active neighborhood proof, then invite signup.", "journey", [("Landing", False), ("Local preview", True), ("Account created", False)]),
            ("02", "Map content view through first post or inquiry", "Growth follows participation. We'd start by instrumenting visit through first meaningful action.", "funnel", [("Page view", 100, False), ("Explore feed", 52, False), ("First action", 14, True)]),
            ("03", "Segment organic neighborhoods for cohort reporting", "Content tests need clean reads. We'd start by tagging users by landing neighborhood.", None, None),
        ],
        "measures": [
            "Organic visitors scrolling past hero content.",
            "Signups per 1,000 neighborhood landing views.",
            "First user action within seven days of signup.",
        ],
    },
    {
        "slug": "copilot",
        "name": "CoPilot",
        "logo_ext": "svg",
        "about": "Consumer app simplifying browse-to-buy for new and used vehicles.",
        "headline": "We believe we can help CoPilot lift finance-prequalified shoppers to dealer visit by 30%.",
        "insight": "You are streamlining the jump from browsing to purchase, including financing and dealer handoffs. Shoppers still stall when monthly payment and dealer next steps are unclear before they commit time.",
        "opps": [
            ("01", "Show payment range and dealer fit before lead send", "Auto finance anxiety is real. We'd start by previewing payment band and dealer match, then submit lead.", "journey", [("Vehicle saved", False), ("Payment preview", True), ("Lead sent", False)]),
            ("02", "Map save-through-scheduled dealer visit", "Dealers measure appointments. We'd start by tracking vehicle save through scheduled visit.", "funnel", [("Vehicle saved", 100, False), ("Pre-qual complete", 62, False), ("Visit scheduled", 38, True)]),
            ("03", "Keep in-app and dealer comms on one timeline", "Handoff confusion kills deals. We'd start by aligning status for shopper and dealer.", None, None),
        ],
        "measures": [
            "Saved vehicles producing a pre-qual attempt.",
            "Dealer visits scheduled within five days of pre-qual.",
            "Closed sales per 100 leads by acquisition source.",
        ],
    },
    {
        "slug": "modak",
        "name": "Modak",
        "logo_ext": "svg",
        "about": "Gamified banking and financial learning app for teens and families.",
        "headline": "We believe we can help Modak lift parent-approved account activation to 50% of teen signups.",
        "insight": "You are leveling up product experience with design hires on a gamified money ecosystem. Teens and parents still need to see value before they link funding and permissions.",
        "opps": [
            ("01", "Let teens preview rewards before parent approval", "Teens drive interest, parents gate money. We'd start by showing earn mechanics, then request parent connect.", "journey", [("Teen signup", False), ("Rewards preview", True), ("Parent approved", False)]),
            ("02", "Map teen invite through first funded transaction", "Activation requires money moving. We'd start by tracking invite through first spend or save.", "funnel", [("Teen invite", 100, False), ("Parent linked", 55, False), ("First transaction", 36, True)]),
            ("03", "Keep learning quests and banking status aligned", "Gamification can confuse. We'd start by using one progress language across features.", None, None),
        ],
        "measures": [
            "Teen signups receiving parent approval within seven days.",
            "First funded transaction within 14 days of approval.",
            "Weekly active teens among funded accounts.",
        ],
    },
    {
        "slug": "trustworthy",
        "name": "Trustworthy",
        "logo_ext": "svg",
        "about": "Family Operating System automating organization across email, docs, and accounts.",
        "headline": "We believe we can help Trustworthy lift Trustworthy NEXT activation to 45% of existing families.",
        "insight": "You launched Trustworthy NEXT to connect inboxes, documents, and accounts automatically. Families still pause when permissions feel broad before they see the first organized output.",
        "opps": [
            ("01", "Show a sample Family OS dashboard before broad permissions", "Automation spooks people. We'd start by previewing organized output from a demo inbox, then request connections.", "journey", [("Upgrade prompt", False), ("Dashboard preview", True), ("First connection", False)]),
            ("02", "Map upgrade through first automated filing", "Value is action, not settings. We'd start by tracking upgrade through first doc auto-sorted.", "funnel", [("NEXT started", 100, False), ("Account linked", 61, False), ("First auto-file", 43, True)]),
            ("03", "Stage rollouts by family size and doc volume", "Cohorts differ. We'd start by tailoring onboarding intensity per household profile.", None, None),
        ],
        "measures": [
            "Existing families starting NEXT within 14 days of prompt.",
            "First automated document within 48 hours of linking.",
            "Second connection added within 30 days.",
        ],
    },
    {
        "slug": "hoopt",
        "name": "HOOPT",
        "logo_ext": "svg",
        "about": "AI-powered lifestyle app expanding with HOOPT Baja and deeper engagement features.",
        "headline": "We believe we can help HOOPT lift HOOPT Baja feature adoption to 40% of active users.",
        "insight": "You shipped HOOPT Baja as your biggest release while hiring for AI and front-end depth. Users still need a clear first win in the new experience before they explore the rest of the platform.",
        "opps": [
            ("01", "Guide users to one Baja outcome in the first session", "Big releases overwhelm. We'd start by delivering one satisfying Baja moment, then invite deeper exploration.", "journey", [("App open", False), ("Baja moment", True), ("Profile depth", False)]),
            ("02", "Map existing users through first Baja completion", "Upsell within base matters. We'd start by instrumenting legacy users through first Baja task done.", "funnel", [("Update seen", 100, False), ("Baja started", 58, False), ("Baja complete", 37, True)]),
            ("03", "Align AI assistant cues with Baja visuals", "New surfaces must feel one product. We'd start by reusing the same trust components in AI and Baja flows.", None, None),
        ],
        "measures": [
            "Active users starting Baja within seven days of release.",
            "First Baja completion among starters.",
            "Day-seven retention among users who complete Baja once.",
        ],
    },
]

EXCLUDE_SLUGS = frozenset({"brave"})
