"""Growth brief content for ICP Leads Wave 1 companies not in outreach JSON."""

# Excluded from generation: Leafwell (cannabis), Citizen (Ciitizen → Citizen Health; see citizen-health/)

BRIEFS_SHEET_WAVE1: list[dict] = [
    {
        "slug": "windscribe",
        "name": "Windscribe",
        "logo_ext": "svg",
        "about": "Privacy VPN and DNS (Control D) used by millions, scaling infrastructure and protocol defaults.",
        "headline": "We believe we can help Windscribe lift first-session protocol adoption to 55% of new installs.",
        "insight": "You are scaling capacity and hardening defaults while navigating regulatory pressure. Users still hesitate on DNS opt-in, protocol choice, and first-run setup before they trust the network long term.",
        "opps": [
            ("01", "Clarify Control D and WireGuard choices at first run", "Defaults only work when the tradeoffs are obvious. We'd start by reframing protocol and DNS opt-in before account creation.", "journey", [("Install", False), ("Protocol clarity", True), ("Connected", False)]),
            ("02", "Map install through seven-day active use", "Adoption shows up in sustained sessions. We'd start by instrumenting first connect through week-one retention.", "funnel", [("Install", 100, False), ("First connect", 71, False), ("Day-7 active", 48, True)]),
            ("03", "Align migration banners with in-app status", "Infrastructure moves create anxiety. We'd start by mirroring migration state in one calm progress pattern.", None, None),
        ],
        "measures": [
            "New installs completing first connect within 24 hours.",
            "Control D opt-in among users who see the prompt.",
            "Day-seven retention among accounts with a successful first session.",
        ],
    },
    {
        "slug": "spetz",
        "name": "Spetz",
        "logo_ext": "svg",
        "about": "AI marketplace matching consumers to nearby service pros in seconds across four countries.",
        "headline": "We believe we can help Spetz lift booking completion to 50% of matched requests.",
        "insight": "You are scaling Sonic-facing product lines and institutional onboarding alongside the consumer marketplace. Users still drop when commitment to book or stake feels risky before they see pro quality and timing.",
        "opps": [
            ("01", "Surface pro rating and ETA before booking commit", "Speed only converts with trust. We'd start by showing who is coming and when, then ask for payment.", "journey", [("Match found", False), ("Pro proof shown", True), ("Booking confirmed", False)]),
            ("02", "Map match through completed service", "Marketplace value is jobs done. We'd start by tracking match through job complete per market.", "funnel", [("Match", 100, False), ("Booked", 62, False), ("Job complete", 41, True)]),
            ("03", "Template launch flows for new partner markets", "Each region launches differently. We'd start by reusing one partner-ready booking shell per integration.", None, None),
        ],
        "measures": [
            "Matched requests reaching confirmed booking.",
            "Median time from match to confirm under five minutes.",
            "Repeat bookings within 30 days of first job.",
        ],
    },
    {
        "slug": "super-unlimited",
        "name": "Super Unlimited",
        "logo_ext": "svg",
        "about": "Mobile app studio acquiring and scaling subscription and ad-based consumer apps globally.",
        "headline": "We believe we can help Super Unlimited lift trial-to-paid conversion to 40% on flagship VPN onboarding.",
        "insight": "You turn massive organic distribution into portfolio revenue through acquisitions and in-app monetization. New users still bounce when permissions, identity prompts, and paywalls stack before they feel value.",
        "opps": [
            ("01", "Sequence permissions after a clear free benefit", "VPN users need a win first. We'd start by delivering connectivity proof, then request notifications and subscription.", "journey", [("Open app", False), ("Free connect proof", True), ("Trial started", False)]),
            ("02", "Map install through day-three paid status", "M&A readiness needs predictable conversion. We'd start by cohorting install through paid by acquisition source.", "funnel", [("Install", 100, False), ("Trial start", 54, False), ("Paid day 3", 38, True)]),
            ("03", "Reuse one onboarding shell across acquired apps", "Portfolio scale needs patterns. We'd start by standardizing first-run and paywall components across two apps.", None, None),
        ],
        "measures": [
            "Installs starting trial within 48 hours.",
            "Paid conversion among trial starters by app.",
            "Day-seven retention among paid accounts.",
        ],
    },
    {
        "slug": "intrivo",
        "name": "Intrivo",
        "logo_ext": "svg",
        "about": "AI healthcare platform scaling consumer test activation and partner result reporting.",
        "headline": "We believe we can help Intrivo lift test activation to 60% of app installs within seven days.",
        "insight": "You are expanding channels and partners after major awards while serving a large app base. Patients still stall when activating a test or reading results before they understand what happens next.",
        "opps": [
            ("01", "Walk users through a sample result before kit activation", "Healthcare moments need clarity. We'd start by previewing a result timeline, then prompt kit registration.", "journey", [("App open", False), ("Result preview", True), ("Kit activated", False)]),
            ("02", "Map install through first result viewed", "Partners judge you on completion. We'd start by instrumenting install through first reported result.", "funnel", [("Install", 100, False), ("Kit linked", 58, False), ("Result viewed", 44, True)]),
            ("03", "Align partner enablement with the same patient milestones", "B2B rollouts need one language. We'd start by mirroring in-app milestones in partner materials.", None, None),
        ],
        "measures": [
            "Installs activating a test within seven days.",
            "First result viewed within 24 hours of activation.",
            "Repeat test orders among activated users.",
        ],
    },
    {
        "slug": "homma",
        "name": "HOMMA",
        "logo_ext": "svg",
        "about": "Tech-forward home builder delivering smart-home living across U.S. and Japan communities.",
        "headline": "We believe we can help HOMMA lift resident smart-home activation to 70% within 14 days of move-in.",
        "insight": "You are turning prototypes into multi-unit and partner-backed communities. Residents still need a polished move-in and leasing path before they adopt the HOMMA platform day to day.",
        "opps": [
            ("01", "Preview the resident app during leasing tours", "Commitment starts before keys. We'd start by demoing smart-home control on tour, then capture move-in setup.", "journey", [("Tour", False), ("App preview", True), ("Move-in setup", False)]),
            ("02", "Map lease signed through first automation used", "Adoption is daily use. We'd start by tracking move-in through first scheduled scene or device.", "funnel", [("Lease signed", 100, False), ("App account", 65, False), ("First automation", 46, True)]),
            ("03", "Package partner launch kits per building type", "Each community differs. We'd start by templating partner rollout materials by property profile.", None, None),
        ],
        "measures": [
            "Move-ins completing app setup within 14 days.",
            "First smart-home automation within seven days of setup.",
            "Partner communities hitting activation targets at launch.",
        ],
    },
    {
        "slug": "lasting",
        "name": "Lasting at Talkspace",
        "logo_ext": "svg",
        "about": "Couples counseling subscription inside Talkspace's telebehavioral-health platform.",
        "headline": "We believe we can help Lasting lift subscription start to 45% of store visitors who complete onboarding.",
        "insight": "You are scaling guided couples counseling inside a larger care platform. Couples still hesitate on subscription and first session when Talkspace integration and expectations are unclear.",
        "opps": [
            ("01", "Show the first guided session before paywall", "Couples need emotional safety. We'd start by previewing session one format, then invite subscription.", "journey", [("Landing", False), ("Session preview", True), ("Subscribed", False)]),
            ("02", "Map onboarding through first exercise completed", "Retention follows early progress. We'd start by tracking signup through first guided exercise done.", "funnel", [("Onboarding", 100, False), ("Plan chosen", 63, False), ("First exercise", 42, True)]),
            ("03", "Clarify Talkspace handoff in-product", "Integrated brands confuse. We'd start by labeling when Talkspace therapy is available versus Lasting paths.", None, None),
        ],
        "measures": [
            "Onboarding completions starting a paid plan.",
            "First exercise finished within 48 hours of subscribe.",
            "Week-four retention among couples who finish exercise one.",
        ],
    },
    {
        "slug": "tenantpay",
        "name": "TenantPay",
        "logo_ext": "svg",
        "about": "Digital rent payments with credit reporting and rewards for tenants and property managers in Canada.",
        "headline": "We believe we can help TenantPay lift credit-reporting enrollment to 55% of active payers.",
        "insight": "You are deepening tenant engagement with Equifax reporting, rewards, and platform integrations. Renters still skip credit enrollment when payment method choice and fee transparency feel murky.",
        "opps": [
            ("01", "Show credit impact before payment method selection", "Reporting needs motivation. We'd start by previewing score-building, then ask for enrollment and pay method.", "journey", [("Rent due", False), ("Credit preview", True), ("Enrolled + paid", False)]),
            ("02", "Map first payment through credit reporting active", "Partnerships amplify enrolled payers. We'd start by tracking first pay through reporting confirmed.", "funnel", [("Account", 100, False), ("First payment", 72, False), ("Credit active", 49, True)]),
            ("03", "Align Yardi and QuickBooks flows with tenant milestones", "PM tools need the same story. We'd start by mirroring tenant status language in manager dashboards.", None, None),
        ],
        "measures": [
            "Active payers enrolling in credit reporting within 30 days.",
            "On-time rent streaks among enrolled tenants.",
            "Property managers adopting rewards per building cohort.",
        ],
    },
    {
        "slug": "marble",
        "name": "Marble at The Zebra",
        "logo_ext": "svg",
        "about": "Insurance policy management experience now part of The Zebra's comparison platform.",
        "headline": "We believe we can help Marble lift policy-link completion to 60% of Zebra users who start connect.",
        "insight": "You are integrating identity-focused policy tools into The Zebra's audience. Users still abandon when linking sensitive policies before they see organized coverage and renewal clarity.",
        "opps": [
            ("01", "Preview organized policies before credential link", "Insurance data feels high stakes. We'd start by showing a sample dashboard, then request link.", "journey", [("Zebra entry", False), ("Policy preview", True), ("Linked", False)]),
            ("02", "Map start connect through first renewal insight", "Value is ongoing management. We'd start by tracking link start through first actionable renewal nudge.", "funnel", [("Connect started", 100, False), ("Policy linked", 64, False), ("Insight delivered", 43, True)]),
            ("03", "Keep Marble and Zebra visual language consistent", "Acquisition users notice seams. We'd start by aligning typography and trust badges across both surfaces.", None, None),
        ],
        "measures": [
            "Started connections finishing policy link.",
            "First insight delivered within 48 hours of link.",
            "Return visits within 30 days among linked users.",
        ],
    },
    {
        "slug": "tiicker",
        "name": "TiiCKER",
        "logo_ext": "svg",
        "about": "Shareholder perks and RetailID verification connecting investors to brand rewards.",
        "headline": "We believe we can help TiiCKER lift brokerage verification completion to 50% of perk claim starts.",
        "insight": "You are scaling TickerPerks and RetailID for consumers and public companies. Investors still drop during multi-step brokerage linking before they claim their first perk.",
        "opps": [
            ("01", "Show a claimed perk before brokerage OAuth", "Verification needs a payoff. We'd start by previewing a real perk outcome, then open linking.", "journey", [("Perk browse", False), ("Perk preview", True), ("Broker linked", False)]),
            ("02", "Map claim start through verified holdings", "B2B rollouts need completion rates. We'd start by instrumenting claim through verified status.", "funnel", [("Claim started", 100, False), ("Broker OAuth", 61, False), ("Holdings verified", 47, True)]),
            ("03", "Unify web and mobile linking steps", "Channels split effort. We'd start by using the same step labels and error recovery on both.", None, None),
        ],
        "measures": [
            "Claim starts completing brokerage verification.",
            "First perk redeemed within seven days of verify.",
            "Enterprise deployments hitting verification targets at launch.",
        ],
    },
    {
        "slug": "catchcorner",
        "name": "CatchCorner",
        "logo_ext": "svg",
        "about": "Sports Illustrated–branded app for booking courts and activities across North America.",
        "headline": "We believe we can help CatchCorner lift booking completion to 55% of facility views.",
        "insight": "You are expanding through CityPickle and Google Reserve into high-demand urban racquet sports. Athletes still abandon at the commit step when court time, price, and SI-quality expectations are not crystal clear.",
        "opps": [
            ("01", "Lock court, price, and cancellation before payment", "Urban sports bookings are high intent. We'd start by summarizing the slot, then ask for payment.", "journey", [("Facility view", False), ("Slot summary", True), ("Booked", False)]),
            ("02", "Map search through check-in at facility", "Retention is showing up. We'd start by tracking discovery through completed reservation.", "funnel", [("Search", 100, False), ("Slot held", 68, False), ("Paid booking", 46, True)]),
            ("03", "Onboard new venues with the same commit pattern", "Network growth must feel consistent. We'd start by templating venue launch flows to the SI standard.", None, None),
        ],
        "measures": [
            "Facility views converting to paid bookings.",
            "Repeat bookings within 30 days per user.",
            "New venues hitting booking targets in launch month.",
        ],
    },
    {
        "slug": "incogni",
        "name": "Incogni",
        "logo_ext": "svg",
        "about": "Personal data removal across 180+ brokers, expanding into Ironwall for high-risk professionals.",
        "headline": "We believe we can help Incogni lift Ironwall onboarding completion to 65% of qualified signups.",
        "insight": "You are growing beyond core removal into Ironwall for executives and sensitive roles. Those customers still pause when sharing details before they understand scope, timeline, and ongoing protection.",
        "opps": [
            ("01", "Show removal scope and timeline before sensitive intake", "High-risk users need proof. We'd start by previewing broker coverage, then collect details.", "journey", [("Landing", False), ("Scope preview", True), ("Intake complete", False)]),
            ("02", "Map signup through first removal confirmation", "Activation is tangible progress. We'd start by tracking signup through first broker confirmation email.", "funnel", [("Signup", 100, False), ("Intake done", 66, False), ("First removal", 44, True)]),
            ("03", "Keep Ironwall and core Incogni trust components aligned", "Two lines, one brand. We'd start by reusing consent and status patterns across products.", None, None),
        ],
        "measures": [
            "Qualified signups finishing Ironwall intake.",
            "First broker removal confirmed within 14 days.",
            "Renewal among accounts with three or more confirmations.",
        ],
    },
    {
        "slug": "diem-app",
        "name": "Diem",
        "logo_ext": "svg",
        "about": "On-demand home services marketplace across 30 U.S. and Canadian cities.",
        "headline": "We believe we can help Diem lift first-booking completion to 50% of new app installs.",
        "insight": "You are scaling verified providers into more homes as you enter new cities. First-time customers still hesitate when provider arrival, scope, and pricing are unclear before they confirm.",
        "opps": [
            ("01", "Show provider profile and arrival proof before confirm", "Home access needs confidence. We'd start by surfacing verified pro details, then ask for booking.", "journey", [("Service pick", False), ("Pro profile", True), ("Booked", False)]),
            ("02", "Map install through first completed job", "Repeat revenue follows job one. We'd start by tracking install through service complete.", "funnel", [("Install", 100, False), ("Booked", 59, False), ("Job complete", 41, True)]),
            ("03", "Localize first-booking copy per city launch", "Markets differ by season and service mix. We'd start by tuning promises per metro cohort.", None, None),
        ],
        "measures": [
            "New installs booking within seven days.",
            "First jobs completed within 48 hours of booking.",
            "Second booking within 30 days of the first.",
        ],
    },
    {
        "slug": "otozen",
        "name": "OtoZen",
        "logo_ext": "svg",
        "about": "Family driving safety app with live location, crash response, and teen driver coaching.",
        "headline": "We believe we can help OtoZen lift family circle activation to 55% of primary account signups.",
        "insight": "You help families share location and driving feedback safely. Members still stall on permissions, emergency contacts, and crash alerts before the circle feels useful.",
        "opps": [
            ("01", "Stage permissions after one safety outcome preview", "Families need a why. We'd start by showing crash response value, then request location access.", "journey", [("Signup", False), ("Safety preview", True), ("Circle linked", False)]),
            ("02", "Map primary signup through two members active", "Networks need density. We'd start by tracking invite through second member online.", "funnel", [("Primary signup", 100, False), ("Invite sent", 67, False), ("Two members active", 46, True)]),
            ("03", "Introduce driving feedback with clear teen vs parent roles", "Coaching can feel surveillance. We'd start by framing feedback language for both roles.", None, None),
        ],
        "measures": [
            "Primary accounts inviting a second member within seven days.",
            "Location sharing active among circles with two members.",
            "Day-fourteen retention among activated families.",
        ],
    },
    {
        "slug": "quicktutor",
        "name": "QuickTutor",
        "logo_ext": "svg",
        "about": "Real-time tutoring marketplace expanding across app stores and international markets.",
        "headline": "We believe we can help QuickTutor lift first session booked to 45% of new tutor and learner signups.",
        "insight": "You are moving from iOS MVP toward multi-platform and global availability. Users still drop on booking, payment, and first-session entry when flows differ by platform or region.",
        "opps": [
            ("01", "Preview a booked session before payment capture", "Knowledge marketplaces need trust. We'd start by showing tutor, time, and price, then charge.", "journey", [("Match", False), ("Session preview", True), ("Paid booking", False)]),
            ("02", "Map signup through first completed session", "Multi-platform launch needs one funnel. We'd start by instrumenting signup through session complete by store.", "funnel", [("Signup", 100, False), ("Booking made", 58, False), ("Session done", 40, True)]),
            ("03", "Align 3.0 onboarding across Apple platforms first", "Release windows are tight. We'd start by reusing components across iOS, iPad, and macOS paths.", None, None),
        ],
        "measures": [
            "Signups making a first booking within seven days.",
            "First sessions completed within 48 hours of booking.",
            "Repeat sessions within 14 days of the first.",
        ],
    },
    {
        "slug": "gofree",
        "name": "GoFree",
        "logo_ext": "svg",
        "about": "Social neobank for chat-native cross-border payments across 16+ countries.",
        "headline": "We believe we can help GoFree lift first inbound payment to 50% of verified accounts within seven days.",
        "insight": "You make cross-border money movement feel like messaging with local and foreign accounts in one place. New users still pause when adding accounts or confirming their first payment in chat.",
        "opps": [
            ("01", "Show a completed chat payment before KYC finish", "Social payments need social proof. We'd start by demoing a received payment, then finish verification.", "journey", [("Signup", False), ("Payment demo", True), ("First receive", False)]),
            ("02", "Map verify through first send or receive", "Activation is money moving. We'd start by tracking verification through first successful transfer.", "funnel", [("Verified", 100, False), ("Account linked", 64, False), ("First transfer", 45, True)]),
            ("03", "Clarify multi-currency balances in chat receipts", "Two account types confuse. We'd start by labeling NGN versus USD balances on every confirmation.", None, None),
        ],
        "measures": [
            "Verified accounts receiving funds within seven days.",
            "First outbound transfer within 14 days of first receive.",
            "Weekly active senders among funded accounts.",
        ],
    },
    {
        "slug": "gride-technology",
        "name": "Gride Technology",
        "logo_ext": "svg",
        "about": "On-demand rides, delivery, and event transport in one super-app experience.",
        "headline": "We believe we can help Gride lift event transport bookings to 40% of match-day app opens.",
        "insight": "You are bundling ride-hailing, delivery, and event transport around high-demand moments like major tournaments. Fans still abandon when match-day booking, pricing, and driver ETA are unclear.",
        "opps": [
            ("01", "Pre-fill event venues and surge expectations upfront", "Event demand spikes fast. We'd start by anchoring venue and price before rider commits.", "journey", [("Event browse", False), ("Venue + price set", True), ("Ride booked", False)]),
            ("02", "Map app open through completed event ride", "Campaigns need completion. We'd start by tracking event landing through drop-off.", "funnel", [("Event open", 100, False), ("Quote accepted", 62, False), ("Ride complete", 38, True)]),
            ("03", "Unify restaurant and ride status in one timeline", "Super-app users expect one feed. We'd start by aligning ETA components across services.", None, None),
        ],
        "measures": [
            "Event opens converting to confirmed rides.",
            "On-time pickups within promised window for event cohorts.",
            "Repeat event bookings across two match days.",
        ],
    },
    {
        "slug": "jiffy",
        "name": "Jiffy",
        "logo_ext": "svg",
        "about": "On-demand marketplace matching homeowners to vetted trades in minutes.",
        "headline": "We believe we can help Jiffy lift booking confirmation to 55% of started service requests.",
        "insight": "You promise effortless home maintenance with pros at the door fast. Homeowners still abandon when price, arrival window, and pro identity are unclear before they confirm.",
        "opps": [
            ("01", "Show pro credentials and all-in price before confirm", "Home repair spikes anxiety. We'd start by surfacing who is coming and total cost, then book.", "journey", [("Service pick", False), ("Pro + price", True), ("Confirmed", False)]),
            ("02", "Map request start through job complete", "Completed jobs drive repeat. We'd start by tracking start through finished work.", "funnel", [("Request started", 100, False), ("Confirmed", 67, False), ("Job complete", 44, True)]),
            ("03", "Align arrival SMS with in-app ETA", "Split updates drive calls. We'd start by mirroring the same milestones in both channels.", None, None),
        ],
        "measures": [
            "Started requests reaching confirmed appointment.",
            "Median confirm time under eight minutes on mobile.",
            "Repeat bookings within 45 days of first job.",
        ],
    },
    {
        "slug": "kaly",
        "name": "Kaly",
        "logo_ext": "svg",
        "about": "Healthtech platform using ML to match patients to the right doctors faster.",
        "headline": "We believe we can help Kaly lift doctor shortlist saves to 60% of completed intake flows.",
        "insight": "You reduce inappropriate care spend by making doctor choice data-driven. Patients still hesitate at the selection moment when algorithmic matches are not translated into clear confidence.",
        "opps": [
            ("01", "Explain why each doctor fits before shortlist save", "ML needs narrative. We'd start by showing match reasons on each card, then invite save or book.", "journey", [("Intake done", False), ("Match reasons", True), ("Shortlist saved", False)]),
            ("02", "Map intake start through appointment request", "Value is booking the right visit. We'd start by tracking intake through requested appointment.", "funnel", [("Intake started", 100, False), ("Matches shown", 70, False), ("Appointment requested", 48, True)]),
            ("03", "Package employer and payer views of match quality", "B2B buyers need proof. We'd start by surfacing appropriateness metrics per cohort for partners.", None, None),
        ],
        "measures": [
            "Completed intakes saving at least one doctor.",
            "Appointment requests within seven days of shortlist.",
            "Patient-reported fit score after first visit.",
        ],
    },
]

SHEET_SKIP_NAMES = frozenset({"Leafwell", "Citizen"})
